config/routes.rb
Rails.application.routes.draw do
  root to: 'profile#dashboard'
  get 'profile/transactions'

  devise_for :users

  namespace :admin do
    resources :accounts
    resources :users
  end

  resources :users, only: %i[show edit update] do
    resources :accounts
  end

  resources :accounts, only: [] do
    resources :deposits, only: %i[new create]
    resources :withdrawals, only: %i[new create]
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show update] do
        resources :accounts
      end

      resources :accounts, only: [] do
        resources :deposits, only: [:create]
        resources :withdrawals, only: [:create]
      end
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :balance, presence: true

  has_many :money_operations, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < BaseController
  before_action :authenticate_user!
  before_action :account, only: %i[show edit update destroy]

  def index
    authorize index_accounts
  end

  def show
    authorize account
  end

  def new
    authorize new_account
  end

  def edit
    authorize account
  end

  def create
    authorize create_account
    if create_account.save
      redirect_to root_path, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize account
    if account.update(account_params)
      redirect_to root_path, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize account
    account.destroy
    redirect_to root_path, notice: 'Account was successfully destroyed.'
  end

  private

  def account
    @account = current_user.accounts.find(params[:id])
  end

  def new_account
    @account = Account.new
  end

  def create_account
    @account = Account.new(account_params)
  end

  def index_accounts
    @accounts = current_user.accounts
  end

  def account_params
    params.require(:account).permit(:user_id, :balance, :currency)
  end
end

app/controllers/admin/accounts_controller.rb
module Admin
  class AccountsController < Admin::BaseController
    before_action :authenticate_user!
    before_action :set_account, only: %i[show edit update destroy]

    def index
      @accounts = Account.all.includes(:user)
    end

    def show; end

    def new
      @account = Account.new
    end

    def edit; end

    def create
      if new_account.save
        redirect_to admin_accounts_path, notice: 'Account was successfully created.'
      else
        render :new
      end
    end

    def update
      if set_account.update(account_params)
        redirect_to admin_accounts_path, notice: 'Account was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      set_account.destroy
      redirect_to admin_accounts_path, notice: 'Account was successfully destroyed.'
    end

    private

    def set_account
      @account = Account.find(params[:id])
    end

    def new_account
      @account = Account.new(account_params)
    end

    def account_params
      params.require(:account).permit(:user_id, :balance, :currency)
    end
  end
end

app/controllers/api/v1/accounts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AccountsController < BaseController
      DELETE_RECORD = 'record deleted'

      def index
        render json: accounts, each_serializer: AccountSerializer
      end

      def show
        render json: account, each_serializer: AccountSerializer
      end

      def create
        account = Account.new(account_params)

        if account.save
          render json: account, status: :created
        else
          render json: account.errors, status: :unprocessable_entity
        end
      end

      def destroy
        account.destroy
        render json: { message: DELETE_RECORD }, status: :ok
      end

      private

      def user
        @user ||= User.find(params[:user_id])
      end

      def account
        @account ||= user.accounts.find(params[:id])
      end

      def accounts
        @accounts ||= user.accounts.includes(:money_operations)
      end

      def account_params
        params.require(:account).permit(:user_id, :balance, :currency)
      end
    end
  end
end

app/views/admin/accounts/_form.html.haml
= form_with(model: [ :admin, account ], local: true) do |form|
  - if account.errors.any?
    #error_explanation
      %h2
        = pluralize(account.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - account.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :user
    = form.select(:user_id, UserHelper.user_id_name)
  .field
    = form.label :balance
    = form.text_field :balance
  .field
    = form.label :currency
    = form.text_field :currency
  .actions
    = form.submit

app/views/admin/accounts/edit.html.haml
%h1 Editing Account
= render 'form', account: @account
= link_to 'Show', admin_account_path(@account)
|
= link_to 'Back', admin_accounts_path

app/views/admin/accounts/index.html.haml
%p#notice= notice
%h1 Accounts
%table
  %thead
    %tr
      %th User
      %th Balance
      %th Currency
      %th{:colspan => "3"}
  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.user.name
        %td= account.balance
        %td= account.currency
        %td= link_to 'Show', admin_account_path(account)
        %td= link_to 'Edit', edit_admin_account_path(account)
        %td= link_to 'Destroy', admin_account_path(account), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Account', new_admin_account_path

app/views/admin/accounts/new.html.haml
%h1 New Account
= render 'form', account: @account
= link_to 'Back', root_path

app/views/admin/accounts/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @account.user.name
%p
  %strong Balance:
  = @account.balance
%p
  %strong Currency:
  = @account.currency
= link_to 'Edit', edit_admin_account_path(@account)
|
= link_to 'Back', admin_accounts_path