config/routes.rb
Rails.application.routes.draw do
  root to: 'profile#dashboard'
  get 'profile/transactions'

  devise_for :users

  namespace :admin do
    resources :accounts
    resources :users
  end

  resources :users, only: %i[show edit update] do
    resources :accounts
  end

  resources :accounts, only: [] do
    resources :deposits, only: %i[new create]
    resources :withdrawals, only: %i[new create]
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show update] do
        resources :accounts
      end

      resources :accounts, only: [] do
        resources :deposits, only: [:create]
        resources :withdrawals, only: [:create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accounts, dependent: :destroy

  has_secure_token :token

  before_destroy :nope

  private

  def nope
    raise 'nope!'
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    before_action :authenticate_user!
    before_action :set_user, only: %i[show edit update destroy]

    def index
      @users = User.all
    end

    def show; end

    def new
      @user = User.new
    end

    def edit; end

    def create
      if new_user.save
        redirect_to admin_users_path, notice: 'User was successfully created.'
      else
        render :new
      end
    end

    def update
      if set_user.update(user_params)
        redirect_to admin_users_path, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      set_user.destroy
      redirect_to admin_users_path, notice: 'User was successfully destroyed.'
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def new_user
      @user = User.new(user_params)
    end

    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseController
      def show
        render json: user, each_serializer: UserSerializer
      end

      def update
        if user.update(user_params)
          render json: user, each_serializer: UserSerializer
        else
          render json: user.errors, status: :unprocessable_entity
        end
      end

      private

      def user
        @user ||= User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:name, :password, :email)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :authenticate_user!
  before_action :user, only: %i[show edit update]

  def show
    authorize user
  end

  def edit
    authorize user
  end

  def update
    authorize user
    if user.update(user_params)
      redirect_to user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  def user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :email)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def self.user_id_name
    User.all.map do |user|
      [user.name, user.id]
    end
  end
end

app/views/admin/users/_form.html.haml
= form_with(model: [ :admin, user ], local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :password
    = form.text_field :password
  .field
    = form.label :email
    = form.text_field :email
  .actions
    = form.submit

app/views/admin/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', admin_account_path(@user)
|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th Name
      %th Email
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', admin_user_path(user)
        %td= link_to 'Edit', edit_admin_user_path(user)
        %td= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', admin_users_path

app/views/admin/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
%p
  %strong Password:
  = @user.password
= link_to 'Edit', edit_admin_user_path(@user)
|
= link_to 'Back', admin_users_path